### PR TITLE
Add new coaches

### PR DESCRIPTION
**Pull request by Zaknafeyn**

### CODE REVIEW

**Comment by sudodoki** [comment]
Ping @Kottans/owners: previously every time, talking about years I was thinking about them in terms of academic years, so 2012 holds coaches for fall 2012-spring 2013 & so forth and so on. Should we change labels for years to represent that or should we just add 2016 and start adding new coaches there? Also, I'm a bit opposed to the idea of adding coaches before they had at least done at least one lecture - might lean the other way around if other think otherwise.

**Comment by Zaknafeyn** [comment]
Agree with you that coaches should finish course or at least start it to be placed on this board. Lets postpone with this pull request so far till fall.

> Should we change labels for years to represent that or should we just add 2016 and start adding new coaches there?
My vote for changing labels for those lectors who start course this fall to 2016.

**Comment by listochkin** [comment]
My thinking is different, We should highlight coaches that make the course happen. I'd love to see them listed with additional badge "Runs a course NOW!" or something similar.

**Comment by suchov** [comment]
Agree with @listochkin we need to have either guest coaches and regular coaches. Just to separate(highlight) those who made the biggest impact. And I think we can add short description to those coaches.

**Comment by programulya** [comment]
:+1: @suchov could you add it plz?

**Pull request merged**
