### PR TITLE
remove slides section cause they are outdated and we aren't keeping them in shape

### PR DESCRIPTION
**Pull request by suchov**

### CODE REVIEW

**Comment by suchov** [comment]
@programulya @sudodoki what do you think about deleting slides sections from our site and leave them on GitHub as separate repos as they are now?

**Comment by vessi** [comment]
i am slightly against it because from time to time I'm using them. but feel free, anyway. LGTM

**Comment by sudodoki** [comment]
don't think ruby / c# changed that dramatically but whatevs

**Comment by sudodoki** [comment]
also, erlang slides is the most original content that had a lot of work gone into it, would be nice to promote those. And those are not outdated

**Comment by suchov** [comment]
@vessi @sudodoki Agree, but we'll keep them in our GitHub. 
Any suggestion on promotion?

**Comment by programulya** [comment]
:( I would like to leave it as-is or try to update, maybe we will have time to update it guys?

**Comment by suchov** [comment]
got it, @vessi @sudodoki @programulya will close this PR

**Pull request closed without merging**
